
DETECTED_OBJECT_MAP_OLD = {
    'Santa Claus':              0,
    'Amazon':                   1,
    'DHL':                      2,
    'FedEx':                    3,
    'RoyalMail':                4,
    'UPS truck':                5,
    'USPS':                     6,
    'bear':                     7,
    'bicycle':                  8,
    'bird':                     9,
    'bus':                      10,
    'car':                      11,
    'cat':                      12,
    'deer':                     13,
    'dog':                      14,
    'motorcycle':               15,
    'mouse':                    16,
    'person':                   17,
    'pickup':                   18,
    'rabbit':                   19,
    'raccoon':                  20,
    'skunk':                    21,
    'squirrel':                 22,
    'truck':                    23,
    'unknown animal':           24,
    'unknown small animal':     25,
    'fly':                      26,
    'spider':                   27,
}

DETECTED_OBJECT_MAP = {
    'human': {
        'Santa Claus':              { 'num': 0, 'name': 'Santa Claus' },
        'person':                   { 'num': 1, 'name': 'Person' },
    },
    'vehicle': {
        'Amazon':                   { 'num': 0, 'name': 'Amazon' },
        'DHL':                      { 'num': 1, 'name': 'DHL' },
        'FedEx':                    { 'num': 2, 'name': 'FedEx' },
        'RoyalMail':                { 'num': 3, 'name': 'Royal Mail' },
        'UPS truck':                { 'num': 4, 'name': 'UPS' },
        'USPS':                     { 'num': 5, 'name': 'USPS' },
        'bicycle':                  { 'num': 6, 'name': 'Bicycle' },
        'bus':                      { 'num': 7, 'name': 'Bus' },
        'car':                      { 'num': 8, 'name': 'Car' },
        'motorcycle':               { 'num': 9, 'name': 'Motorcycle' },
        'pickup':                   { 'num': 10, 'name': 'Pickup' },
        'truck':                    { 'num': 11, 'name': 'Truck' },
    },
    'animal': {
        'bear':                     { 'num': 0, 'name': 'Bear' },
        'bird':                     { 'num': 1, 'name': 'Bird' },
        'cat':                      { 'num': 2, 'name': 'Cat' },
        'deer':                     { 'num': 3, 'name': 'Deer' },
        'dog':                      { 'num': 4, 'name': 'Dog' },
        'mouse':                    { 'num': 5, 'name': 'Mouse' },
        'rabbit':                   { 'num': 6, 'name': 'Rabbit' },
        'raccoon':                  { 'num': 7, 'name': 'Raccoon' },
        'skunk':                    { 'num': 8, 'name': 'Skunk' },
        'squirrel':                 { 'num': 9, 'name': 'Squirrel' },
        'unknown animal':           { 'num': 10, 'name': 'Unknown Animal' },
        'unknown small animal':     { 'num': 11, 'name': 'Unknown Small Animal' },
    },
    'insect': {
        'fly':                      { 'num':  0, 'name': 'Fly' },
        'spider':                   { 'num':  1, 'name': 'Spider' },
    },

}
